package AdditionApp;


/**
* AdditionApp/AdditionPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Pazim/workspace/Assignment/src/Hello.idl
* Saturday, July 6, 2019 2:13:41 AM EDT
*/

public abstract class AdditionPOA extends org.omg.PortableServer.Servant
 implements AdditionApp.AdditionOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("add", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
    _methods.put ("bookEvent", new java.lang.Integer (2));
    _methods.put ("removeEvent", new java.lang.Integer (3));
    _methods.put ("listEventAvailability", new java.lang.Integer (4));
    _methods.put ("addEvent", new java.lang.Integer (5));
    _methods.put ("getBookingSchedule", new java.lang.Integer (6));
    _methods.put ("cancelEvent", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // AdditionApp/Addition/add
       {
         int a = in.read_long ();
         int b = in.read_long ();
         int $result = (int)0;
         $result = this.add (a, b);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // AdditionApp/Addition/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       case 2:  // AdditionApp/Addition/bookEvent
       {
         String customerID = in.read_string ();
         String eventID = in.read_string ();
         String eventType = in.read_string ();
         String $result = null;
         $result = this.bookEvent (customerID, eventID, eventType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // AdditionApp/Addition/removeEvent
       {
         String eventID = in.read_string ();
         String eventType = in.read_string ();
         String $result = null;
         $result = this.removeEvent (eventID, eventType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // AdditionApp/Addition/listEventAvailability
       {
         String eventType = in.read_string ();
         String $result = null;
         $result = this.listEventAvailability (eventType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // AdditionApp/Addition/addEvent
       {
         String eventID = in.read_string ();
         String eventType = in.read_string ();
         int bookingCapacity = in.read_long ();
         String $result = null;
         $result = this.addEvent (eventID, eventType, bookingCapacity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  //  HashMap<in string,in  HashMap<string, Integer>> getHashMap();
       case 6:  // AdditionApp/Addition/getBookingSchedule
       {
         String customerID = in.read_string ();
         String $result = null;
         $result = this.getBookingSchedule (customerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // AdditionApp/Addition/cancelEvent
       {
         String customerID = in.read_string ();
         String eventID = in.read_string ();
         String eventType = in.read_string ();
         String $result = null;
         $result = this.cancelEvent (customerID, eventID, eventType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AdditionApp/Addition:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Addition _this() 
  {
    return AdditionHelper.narrow(
    super._this_object());
  }

  public Addition _this(org.omg.CORBA.ORB orb) 
  {
    return AdditionHelper.narrow(
    super._this_object(orb));
  }


} // class AdditionPOA
