package AdditionApp;


/**
* AdditionApp/AdditionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Pazim/workspace/Assignment/src/Hello.idl
* Saturday, July 6, 2019 2:13:42 AM EDT
*/

public interface AdditionOperations 
{
  int add (int a, int b);
  void shutdown ();
  String bookEvent (String customerID, String eventID, String eventType);
  String removeEvent (String eventID, String eventType);
  String listEventAvailability (String eventType);
  String addEvent (String eventID, String eventType, int bookingCapacity);

  //  HashMap<in string,in  HashMap<string, Integer>> getHashMap();
  String getBookingSchedule (String customerID);
  String cancelEvent (String customerID, String eventID, String eventType);
} // interface AdditionOperations
