package AdditionApp;


/**
* AdditionApp/Addition.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Pazim/workspace/Assignment/src/Hello.idl
* Saturday, July 6, 2019 2:13:42 AM EDT
*/

public interface Addition extends AdditionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Addition
